version: "3.7"

services:  
  app1:
    image: courselabs/app-1:v2
    build:
      context: ./app-1
      dockerfile: Dockerfile.v2

  app2:
    image: courselabs/app-2:v2
    build:
      context: ./app-2
      dockerfile: Dockerfile.v2